//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlampiadEbtedaee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Group> GroupSet { get; set; }
        public virtual DbSet<Exam> ExamSet { get; set; }
        public virtual DbSet<WinQuestion> WinQuestionSet { get; set; }
        public virtual DbSet<WordQuestion> WordQuestionSet { get; set; }
        public virtual DbSet<ExcelQuestion> ExcelQuestionSet { get; set; }
        public virtual DbSet<PowerPointQuestion> PowerPointQuestionSet { get; set; }
        public virtual DbSet<WindowsTheory> WindowsTheorySet { get; set; }
        public virtual DbSet<WordTheory> WordTheorySet { get; set; }
        public virtual DbSet<ExcelTheory> ExcelTheorySet { get; set; }
        public virtual DbSet<PowerPointTheory> PowerPointTheorySet { get; set; }
        public virtual DbSet<HardwareQuestion> HardwareQuestionSet { get; set; }
    }
}
