//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlampiadEbtedaee
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPointTheory
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string ChoiceOne { get; set; }
        public string PicOne { get; set; }
        public string ChoiceTwo { get; set; }
        public string PicTwo { get; set; }
        public string ChoiceThree { get; set; }
        public string PicThree { get; set; }
        public string ChoiceFour { get; set; }
        public string PicFour { get; set; }
        public string Voice { get; set; }
        public string Level { get; set; }
        public int Grade { get; set; }
        public string Correct { get; set; }
        public string Repeatitive { get; set; }
    }
}
