//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlampiadEbtedaee
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Exam = new HashSet<Exam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string NCode { get; set; }
        public string Father { get; set; }
        public string SchoolName { get; set; }
        public string ClassName { get; set; }
        public int TotalTime { get; set; }
        public int TotalMark { get; set; }
        public System.DateTime ExamDate { get; set; }
        public string Gender { get; set; }
        public int GroupId { get; set; }
        public int ScorePercentage { get; set; }
    
        public virtual ICollection<Exam> Exam { get; set; }
        public virtual Group Group { get; set; }
    }
}
